Repository janosh/awesome-normalizing-flows, pull requests merged in 2024-09, with the labels that each got.

#68 GWKokab a parameter estimation package in domain of astrophysics
  .github/workflows/link-check-config.json
  .pre-commit-config.yaml
  data/packages.yml
  data/publications.yml
  readme.md
Labels: package, jax

#70 Change `authors` to `list[dict['name' | 'url' | ..., str]]`
  data/applications.yml
  data/make_readme.py
  data/packages.yml
  data/posts.yml
  data/publications.yml
  data/repos.yml
  data/videos.yml
  readme.md
Labels: enhancement

#71 Add auto-format yaml pre-commit hook
  .pre-commit-config.yaml
Labels: linting
